// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBodyTemperatureChange();
void onCurrentBpmChange();
void onCadutaChange();
void onWearGlassesChange();

float bodyTemperature;
int currentBpm;
bool caduta;
bool wearGlasses;

void initProperties(){

  ArduinoCloud.addProperty(bodyTemperature, READWRITE, 5 * SECONDS, onBodyTemperatureChange);
  ArduinoCloud.addProperty(currentBpm, READWRITE, 5 * SECONDS, onCurrentBpmChange);
  ArduinoCloud.addProperty(caduta, READWRITE, ON_CHANGE, onCadutaChange, 1);
  ArduinoCloud.addProperty(wearGlasses, READWRITE, 5 * SECONDS, onWearGlassesChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
